global:
  scrape_interval: 7s

scrape_configs:
  - job_name: 'My app'
    scrape_interval: 7s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets: ['localhost:8080']
    basic_auth:
      username: bob@gmail.com
      password: passBob