version: '3'
# Щось типу persistent-storage
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      prom_grafana:
        ipv4_address: 172.31.0.2
  
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    restart: unless-stopped
    networks:
      prom_grafana:
        ipv4_address: 172.31.0.3
    environment:
     - GF_INSTALL_PLUGINS=grafana-image-renderer
     - GF_UNIFIED_ALERTING_SCREENSHOTS_CAPTURE=true

  loki:
    image: grafana/loki:latest
    container_name: loki
  #  ports:
  #    - "3100:3100"
  #  volumes:
  #    - ./loki.yaml:/etc/loki/local-config.yaml
  #  command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    networks:
      prom_grafana:
        ipv4_address: 172.31.0.6

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /home/yaroslav/hosts_warden/log/:/home/yaroslav/hosts_warden/log/
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
    networks:
      prom_grafana:
        ipv4_address: 172.31.0.7

  node_exporter:
      image: quay.io/prometheus/node-exporter:latest
      container_name: node_exporter
      command:
        - '--path.rootfs=/host'
      restart: unless-stopped
      volumes:
        - '/:/host:ro,rslave'
      networks:
        prom_grafana:
          ipv4_address: 172.31.0.4

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    privileged: true
    networks:
      prom_grafana:
        ipv4_address: 172.31.0.5

networks:
  prom_grafana:
    driver: bridge
    ipam:
     config:
       - subnet: 172.31.0.0/16
         gateway: 172.31.0.1