version: '3.8'

services:
  uptime-kuma:
    image: elestio/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "3227:3001"  # <Host Port>:<Container Port>
    restart: always

volumes:
  uptime-kuma: